### ISSUE TITLE
how to use this

### ISSUE THREAD

**Issue by bpmason1** [sile/rustracing#1]
Could you please include a quickstart section to the README with code samples describing the basic usage of this library.

**Comment by warmwaffles** [comment]
I too, would love to see a basic usage of the library. Would be nice to be able to log out to env logger.

**Comment by nevi-me** [comment]
I used the library on one of my projects, hope this helps: https://github.com/MovingGauteng/geofancy-rs/blob/master/src/geofancy_server.rs#L20

**Comment by sile** [comment]
Since `rustracing` is an interface library and not so usefull on its own, I added a link to [rustracing_jaeger] crate to [README.md] as an implementation and a running example of it.

[rustracing_jaeger]: https://github.com/sile/rustracing_jaeger
[README.md]: https://github.com/sile/rustracing/blob/master/README.md
