### ISSUE TITLE
Sharing a Span between threads

### ISSUE THREAD

**Issue by mjkillough** [sile/rustracing#3]
I have a web service which uses `rayon` to compute do multiple operations in parallel. I'd like the work done by each operation to be tracked by a child span of the span showing the whole web request, as the operations are all related.

Currently, `Span` is `!Sync` and does not implement `Clone`, so there doesn't seem to be a way for the different threads to reference the same parent span. 

Is there a reason `Clone` isn't implemented for `Span`? It might also be worth investigating [`crossbeam::channel`](https://docs.rs/crossbeam/0.7.1/crossbeam/channel/struct.Sender.html#impl-Sync), which I think would allow the `Span` to be `Sync`.

**Comment by sile** [comment]
Sorry fo the late reply.
It is intentional that `Span` does not implement `Clone` because if it was allowed, the same span may be reported multiple times. Instead, [`SpanContext`](https://docs.rs/rustracing/0.1.8/rustracing/span/struct.SpanContext.html) which can be retrieved by calling `Span::context()` is available for that purpose.

>  It might also be worth investigating `crossbeam::channel`, which I think would allow the `Span` to be `Sync`.

I'm not familiar with `crossbeam`, but it sounds good to me (contribution is very welcome).

**Comment by mixalturek** [comment]
These PRs seems related but we had different motivation.
- https://github.com/sile/rustracing/pull/4
- https://github.com/sile/rustracing_jaeger/pull/12

**Comment by sile** [comment]
Now `Span` implements `Sync`, so I will close this PR (thanks @mixalturek).
